# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evans < Formula
  desc "Evans: more expressive universal gRPC client"
  homepage "https://evans.syfm.me"
  version "0.9.3"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/ktr0731/evans/releases/download/0.9.3/evans_darwin_amd64.tar.gz"
    sha256 "21d17adddf2f7cec1384ae3577a6272a18237835335f9ca6ab489cc659104dec"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/ktr0731/evans/releases/download/0.9.3/evans_linux_amd64.tar.gz"
    sha256 "166404aab42cceee41b15a47f4f94b4d8725d689293743f767eb1bfc98d971d0"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "http://github.com/ktr0731/evans/releases/download/0.9.3/evans_linux_arm.tar.gz"
    sha256 "16d16dd27d05d16597757e89aa34043c0839e78af657ac38f8599b663e43ba46"
  end

  def install
    bin.install "evans"
  end
end
