# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evans < Formula
  desc "Evans: more expressive universal gRPC client"
  homepage "https://evans.syfm.me"
  version "0.10.5"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.5/evans_darwin_arm64.tar.gz"
      sha256 "4d31337889b97705df7abf00d4a870ede705674247d104e8c4affa249fd8a72c"

      def install
        bin.install "evans"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.5/evans_darwin_amd64.tar.gz"
      sha256 "29761f0f35d29bef62b91be10cb7bb6bda0c93e789f2b6661705ea20e1c95f96"

      def install
        bin.install "evans"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.5/evans_linux_arm.tar.gz"
      sha256 "6a36f5bbd763f253bdca74b76867a0aac03b6dde2137bfa4b54be9043a33076a"

      def install
        bin.install "evans"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.5/evans_linux_arm64.tar.gz"
      sha256 "22474f7b7f6ecf4162d0a470e485f18c84b20c93bacc850d12ce23a7c235bdfe"

      def install
        bin.install "evans"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.5/evans_linux_amd64.tar.gz"
      sha256 "2dad8fe5bfaa15e9de17532657a4cd49733226e9313ac763fd11a5413b2cf98d"

      def install
        bin.install "evans"
      end
    end
  end
end
